using System.Text;
using System.Text.Json;
using Manifesta.Core;
using Manifesta.Core.IR;
using Manifesta.Core.Pipeline;

namespace Manifesta.Doc;

/// <summary>
/// Generates <c>database.md</c> from the resolved IR.
///
/// Produces hierarchical table of contents followed by detailed table documentation,
/// matching the format of professional database model documentation.
///
/// M4 will expand this with HTML output and full ERD support.
/// </summary>
public sealed class DatabaseDocGenerator : IGenerator<ManifestRoot, string>
{
    private static readonly JsonSerializerOptions _json = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Generate documentation from ManifestRoot (implements IGenerator interface).
    /// </summary>
    public string Generate(ManifestRoot ir)
    {
        return GenerateWithOrder(ir, null);
    }

    /// <summary>Generates a DBML file from the resolved IR.</summary>
    public string GenerateDbml(ManifestRoot ir) => new DbmlGenerator().Generate(ir);

    /// <summary>
    /// Generate documentation with explicit section ordering.
    /// </summary>
    /// <param name="ir">The resolved IR.</param>
    /// <param name="sectionOrder">Optional section ordering override.</param>
    /// <param name="title">Optional document title.</param>
    /// <param name="dialect">Markdown dialect for fenced code blocks.</param>
    /// <param name="includeLogicalOverride">CLI override for logical FK inclusion in ERDs.</param>
    /// <param name="includeVirtualOverride">CLI override for virtual FK inclusion in ERDs.</param>
    /// <param name="includeCrossSectionRefs">When <c>true</c> (default), physical FKs that cross
    ///   section boundaries are rendered as labelled external stubs in ERDs. Pass <c>false</c>
    ///   (via <c>--no-cross-section</c>) to restore the original intra-section-only behaviour.</param>
    public string GenerateWithOrder(
        ManifestRoot ir,
        IReadOnlyList<string>? sectionOrder = null,
        string? title = null,
        MarkdownDialect dialect = MarkdownDialect.CommonMark,
        bool? includeLogicalOverride = null,
        bool? includeVirtualOverride = null,
        bool includeCrossSectionRefs = true)
    {
        var sb = new StringBuilder();

        // Reorder sections based on sectionOrder if provided
        var orderedSections = ir.Sections;
        if (sectionOrder != null && sectionOrder.Count > 0)
        {
            orderedSections = ReorderSections(ir.Sections, sectionOrder);
        }

        // Generate title and metadata
        sb.AppendLine($"# {title ?? "DATABASE MODEL"}");
        sb.AppendLine();
        sb.AppendLine($"> Generated by Manifesta on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}");
        sb.AppendLine();

        // Build table lookup early — needed for deprecated TOC rendering
        var tablesByNameForToc = ir.Tables
            .GroupBy(t => t.Name, TableNames.Comparer)
            .ToDictionary(g => g.Key, g => g.First(), TableNames.Comparer);

        // Generate table of contents
        GenerateTableOfContents(sb, orderedSections, tablesByNameForToc);

        // Page break
        sb.AppendLine("\n---\n");

        // Build cross-section map: table name → section display title, for all sections.
        // Used by ErdGenerator to render physical FKs that cross section boundaries as
        // labelled external stubs. Null when cross-section refs are disabled.
        var tableSectionMap = includeCrossSectionRefs
            ? orderedSections
                .SelectMany(s => s.Tables.Select(t => (table: t, sectionTitle: s.DisplayTitle)))
                .GroupBy(x => x.table, TableNames.Comparer)
                .ToDictionary(g => g.Key, g => g.First().sectionTitle, TableNames.Comparer)
            : (IReadOnlyDictionary<string, string>?)null;

        // Generate detailed documentation
        GenerateDetailedDocumentation(sb, orderedSections, ir.Tables, dialect,
            includeLogicalOverride, includeVirtualOverride, tableSectionMap);

        return sb.ToString();
    }

    private static IReadOnlyList<SectionDefinition> ReorderSections(
        IReadOnlyList<SectionDefinition> sections,
        IReadOnlyList<string> sectionOrder)
    {
        var sectionsByName = sections
            .GroupBy(s => s.Name, TableNames.Comparer)
            .ToDictionary(g => g.Key, g => g.First(), TableNames.Comparer);

        var reordered = new List<SectionDefinition>();

        // Add sections in the specified order
        foreach (var sectionName in sectionOrder)
        {
            if (sectionsByName.TryGetValue(sectionName, out var section))
            {
                reordered.Add(section);
                sectionsByName.Remove(sectionName);  // Mark as processed
            }
        }

        // Append any remaining sections that weren't in the order list
        foreach (var section in sectionsByName.Values)
        {
            reordered.Add(section);
        }

        return reordered.AsReadOnly();
    }

    private static void GenerateTableOfContents(
        StringBuilder sb,
        IReadOnlyList<SectionDefinition> sections,
        IReadOnlyDictionary<string, TableDefinition> tablesByName)
    {
        sb.AppendLine("## Table of Contents\n");

        foreach (var section in sections)
        {
            string sectionAnchor = NormalizeAnchor(section.DisplayTitle);
            sb.AppendLine($"- [{section.DisplayTitle}](#{sectionAnchor})");

            if (section.Tables.Count > 0)
            {
                foreach (var tableName in section.Tables)
                {
                    string tableAnchor = NormalizeAnchor(tableName);
                    var isDeprecated   = tablesByName.TryGetValue(tableName, out var t) && t.IsDeprecated;
                    var label          = isDeprecated ? $"~~{tableName}~~" : tableName;
                    var tocSuffix      = t is not null && !string.IsNullOrEmpty(t.ShortDescription)
                                            ? $" - {t.ShortDescription}"
                                            : "";
                    sb.AppendLine($"  - [{label}](#{tableAnchor}){tocSuffix}");
                }
            }
        }

        sb.AppendLine();
    }

    private static string NormalizeAnchor(string text)
    {
        // Convert to lowercase, replace spaces and dots with hyphens
        return text.ToLowerInvariant()
            .Replace(" ", "-")
            .Replace(".", "-")
            .Replace("_", "-")
            .Replace("/", "-");
    }

    private static string EscapeForMarkdownTable(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        // Normalize to LF so we only need one code path.
        var normalized = text.Replace("\r\n", "\n").Replace("\r", "\n");
        var lines      = normalized.Split('\n');

        if (lines.Length == 1)
            return normalized;

        // Between each pair of lines, choose the separator:
        //   • An indented bullet line (leading whitespace followed by '-') → real '\n'
        //     so that Markdown renders it as a nested list item.
        //   • Everything else → '<br/>' to stay compatible with Markdown table cells.
        var sb = new StringBuilder();
        for (int i = 0; i < lines.Length; i++)
        {
            if (i > 0)
            {
                bool isIndentedBullet = lines[i].Length > 0
                    && char.IsWhiteSpace(lines[i][0])
                    && lines[i].TrimStart().StartsWith("-");

                sb.Append(isIndentedBullet ? "\n" : "<br/>");
            }
            sb.Append(lines[i]);
        }

        return sb.ToString();
    }

    private static void GenerateDetailedDocumentation(
        StringBuilder sb,
        IReadOnlyList<SectionDefinition> sections,
        IReadOnlyList<TableDefinition> tables,
        MarkdownDialect dialect = MarkdownDialect.CommonMark,
        bool? includeLogicalOverride = null,
        bool? includeVirtualOverride = null,
        IReadOnlyDictionary<string, string>? tableSectionMap = null)
    {
        // Build a lookup of tables for quick access.
        // Use first-wins on duplicates so we never throw here — callers are expected to
        // catch duplicates earlier and report them with proper file paths.
        var tablesByName = tables
            .GroupBy(t => t.Name, TableNames.Comparer)
            .ToDictionary(g => g.Key, g => g.First(), TableNames.Comparer);

        foreach (var section in sections)
        {
            // Section heading with explicit anchor
            string sectionAnchor = NormalizeAnchor(section.DisplayTitle);
            sb.AppendLine($"<a id=\"{sectionAnchor}\"></a>");
            sb.AppendLine($"## {section.DisplayTitle}\n");

            if (!string.IsNullOrEmpty(section.Description))
            {
                var escapedDescription = EscapeForMarkdownTable(section.Description);
                sb.AppendLine(escapedDescription);
                sb.AppendLine();
            }

            // Render auto-generated ERD diagrams
            if (section.Erds.Count > 0)
            {
                var erdGen = new ErdGenerator();
                foreach (var erd in section.Erds)
                {
                    var effectiveErd = (includeLogicalOverride is not null || includeVirtualOverride is not null)
                        ? erd with
                        {
                            IncludeLogical = includeLogicalOverride ?? erd.IncludeLogical,
                            IncludeVirtual = includeVirtualOverride ?? erd.IncludeVirtual,
                        }
                        : erd;
                    sb.AppendLine(erdGen.Generate(effectiveErd, section.Tables, tablesByName, dialect, tableSectionMap));
                    sb.AppendLine();
                }
            }

            // Document each table in the section
            foreach (var tableName in section.Tables)
            {
                TableDefinition? table = null;
                if (tablesByName.TryGetValue(tableName, out var foundTable))
                {
                    table = foundTable;
                }

                if (table is null)
                {
                    string missingAnchor = NormalizeAnchor(tableName);
                    sb.AppendLine($"<a id=\"{missingAnchor}\"></a>");
                    sb.AppendLine($"### {tableName}");
                    sb.AppendLine("> **Warning**: Definition file missing.\n");
                    continue;
                }

                // Table name as heading with explicit anchor
                // Asterisk suffix signals at least one field description is still AI-generated.
                string tableAnchor      = NormalizeAnchor(table.Name);
                var hasAutoGenFields    = table.Fields.Any(f => f.DescriptionAutoGenerated == true);
                var tableNameDisplay    = hasAutoGenFields ? $"{table.Name}*" : table.Name;
                var tableHeading        = table.IsDeprecated ? $"~~{tableNameDisplay}~~ `[DEPRECATED]`" : tableNameDisplay;
                sb.AppendLine($"<a id=\"{tableAnchor}\"></a>");
                sb.AppendLine($"### {tableHeading}\n");

                // Deprecation notice
                if (table.IsDeprecated)
                {
                    var notice = string.IsNullOrWhiteSpace(table.DeprecationMessage)
                        ? "> **Deprecated.** This table should no longer be used."
                        : $"> **Deprecated.** {EscapeForMarkdownTable(table.DeprecationMessage)}";
                    sb.AppendLine(notice);
                    sb.AppendLine();
                }

                // Description as bullet point
                if (!string.IsNullOrEmpty(table.Description))
                {
                    var escapedTableDesc = EscapeForMarkdownTable(table.Description);
                    sb.AppendLine($"- {escapedTableDesc}");
                    sb.AppendLine();
                }

                // Fields table
                if (table.Fields.Count > 0)
                {
                    // Only emit optional columns when at least one field has a value.
                    var hasDefaults     = table.Fields.Any(f => !string.IsNullOrEmpty(f.Default));
                    var hasComputed     = table.Fields.Any(f => f.IsComputed);
                    var hasSensitivity  = table.Fields.Any(f => f.Sensitivity is not null);

                    // Build header and separator based on which optional columns are present.
                    var header    = "| Field | Type | Nullable |";
                    var separator = "|-------|------|----------|";
                    if (hasDefaults)    { header += " Default |";     separator += "---------|"; }
                    if (hasComputed)    { header += " Expression |";  separator += "------------|"; }
                    if (hasSensitivity) { header += " Sensitivity |"; separator += "------------|"; }
                    header    += " Description |";
                    separator += "-------------|";

                    sb.AppendLine(header);
                    sb.AppendLine(separator);

                    foreach (var field in table.Fields)
                    {
                        var nullable         = field.Nullable ? "✓" : "";
                        var typeCell         = field.IsComputed ? $"{field.Type} `[C]`" : field.Type;
                        var escapedFieldDesc = EscapeForMarkdownTable(field.Description);

                        // Deprecated fields: strikethrough name; append deprecation message footnote
                        var fieldNameCell = field.IsDeprecated ? $"~~{field.Name}~~" : field.Name;

                        var row = $"| {fieldNameCell} | {typeCell} | {nullable} |";
                        if (hasDefaults)
                        {
                            var defaultCell = string.IsNullOrEmpty(field.Default) ? "" : $"`{field.Default}`";
                            row += $" {defaultCell} |";
                        }
                        if (hasComputed)
                        {
                            var exprCell = string.IsNullOrEmpty(field.ComputedExpression) ? "" : $"`{EscapeForMarkdownTable(field.ComputedExpression)}`";
                            row += $" {exprCell} |";
                        }
                        if (hasSensitivity)
                        {
                            var badge = field.Sensitivity?.ToLowerInvariant() switch
                            {
                                "pii"          => "🔴 PII",
                                "confidential" => "🟡 Confidential",
                                "internal"     => "🔵 Internal",
                                "public"       => "🟢 Public",
                                _              => "",
                            };
                            row += $" {badge} |";
                        }

                        // Append deprecation note inside description cell
                        var descCell = escapedFieldDesc;
                        if (field.IsDeprecated && !string.IsNullOrWhiteSpace(field.DeprecationMessage))
                            descCell = string.IsNullOrEmpty(descCell)
                                ? $"*Deprecated: {EscapeForMarkdownTable(field.DeprecationMessage)}*"
                                : $"{descCell} *Deprecated: {EscapeForMarkdownTable(field.DeprecationMessage)}*";
                        row += $" {descCell} |";
                        sb.AppendLine(row);
                    }

                    sb.AppendLine();
                }

                // Primary key
                if (table.PrimaryKey.Count > 0)
                {
                    sb.AppendLine($"**Primary Key**: `{string.Join(", ", table.PrimaryKey)}`");
                    sb.AppendLine();
                }

                // Foreign keys
                if (table.ForeignKeys.Count > 0)
                {
                    sb.AppendLine("**Foreign Keys:**");

                    foreach (var fk in table.ForeignKeys)
                    {
                        var annotations = new List<string>();
                        if (fk.Kind == ForeignKeyKind.Logical) annotations.Add("logical");
                        else if (fk.Kind == ForeignKeyKind.Virtual) annotations.Add("virtual");
                        if (fk.CascadeDelete) annotations.Add("cascades");
                        var suffix = annotations.Count > 0 ? $" ({string.Join(", ", annotations)})" : "";
                        sb.AppendLine($"- `{fk.SourceField}` → `{fk.TargetTable}.{fk.TargetField}`{suffix}");
                    }

                    sb.AppendLine();
                }

                // Indexes
                if (table.Indexes.Count > 0)
                {
                    sb.AppendLine("**Indexes:**");
                    sb.AppendLine();
                    var hasIndexDescriptions = table.Indexes.Any(i => !string.IsNullOrWhiteSpace(i.Description));
                    var idxHeader    = "| Name | Columns | Unique | Clustered | Filter |";
                    var idxSeparator = "|------|---------|--------|-----------|--------|";
                    if (hasIndexDescriptions) { idxHeader += " Description |"; idxSeparator += "-------------|"; }
                    sb.AppendLine(idxHeader);
                    sb.AppendLine(idxSeparator);
                    foreach (var idx in table.Indexes)
                    {
                        var cols      = string.Join(", ", idx.Columns);
                        var unique    = idx.IsUnique    ? "✓" : "";
                        var clustered = idx.IsClustered ? "✓" : "";
                        var filter    = idx.IsFiltered && idx.FilterExpression is not null
                            ? $"`{EscapeForMarkdownTable(idx.FilterExpression)}`"
                            : "";
                        var row = $"| `{idx.Name}` | {cols} | {unique} | {clustered} | {filter} |";
                        if (hasIndexDescriptions)
                            row += $" {EscapeForMarkdownTable(idx.Description ?? "")} |";
                        sb.AppendLine(row);
                    }
                    sb.AppendLine();
                }

                // Constraints
                var hasChecks   = table.CheckConstraints.Count > 0;
                var hasUniques  = table.UniqueConstraints.Count > 0;
                if (hasChecks || hasUniques)
                {
                    sb.AppendLine("**Constraints:**");
                    sb.AppendLine();
                    if (hasChecks)
                    {
                        sb.AppendLine("*CHECK constraints:*");
                        sb.AppendLine();
                        foreach (var cc in table.CheckConstraints)
                        {
                            var scope = cc.Column is not null ? $" (column `{cc.Column}`)" : "";
                            sb.AppendLine($"- `{cc.Name}`{scope}: `{EscapeForMarkdownTable(cc.Expression)}`");
                        }
                        sb.AppendLine();
                    }
                    if (hasUniques)
                    {
                        sb.AppendLine("*UNIQUE constraints:*");
                        sb.AppendLine();
                        foreach (var uc in table.UniqueConstraints)
                            sb.AppendLine($"- `{uc.Name}`: {string.Join(", ", uc.Columns)}");
                        sb.AppendLine();
                    }
                }

                // Reference table data
                if (table.IsReferenceTable && table.Data.Count > 0)
                {
                    // Column order follows table.Fields; orphaned data keys are silently skipped.
                    var columns = table.Fields
                        .Select(f => f.Name)
                        .Where(name => table.Data.Any(row => row.ContainsKey(name)))
                        .ToList();

                    if (columns.Count > 0)
                    {
                        sb.AppendLine("**Reference Data:**");
                        sb.AppendLine();

                        var colHeader    = "| " + string.Join(" | ", columns) + " |";
                        var colSeparator = "|" + string.Join("|", columns.Select(_ => "---")) + "|";
                        sb.AppendLine(colHeader);
                        sb.AppendLine(colSeparator);

                        foreach (var row in table.Data)
                        {
                            var cells = columns.Select(col =>
                            {
                                if (!row.TryGetValue(col, out var element))
                                    return "";
                                return element.ValueKind switch
                                {
                                    System.Text.Json.JsonValueKind.String  => EscapeForMarkdownTable(element.GetString() ?? ""),
                                    System.Text.Json.JsonValueKind.Null    => "",
                                    _                                       => element.GetRawText(),
                                };
                            });
                            sb.AppendLine("| " + string.Join(" | ", cells) + " |");
                        }

                        sb.AppendLine();
                    }
                }

                // Add some spacing between tables
                sb.AppendLine();
            }

            // Section divider
            sb.AppendLine("---\n");
        }
    }
}
