using System.Text.Json;
using FluentAssertions;
using Manifesta.Core;
using Manifesta.Core.IR;
using Manifesta.Core.Pipeline;
using Xunit;

namespace Manifesta.Core.Tests;

public class TableDefinitionSerializerTests
{
    // ── Helpers ───────────────────────────────────────────────────────────────

    private static TableDefinition MinimalTable(string name = "dbo.Order") => new()
    {
        Name       = name,
        Fields     = [new FieldDefinition { Name = "Id", Type = "int" }],
        PrimaryKey = ["Id"],
    };

    private static JsonElement Parse(string json) =>
        JsonDocument.Parse(json).RootElement;

    // ── Mandatory fields ──────────────────────────────────────────────────────

    [Fact]
    public void Serialize_Always_IncludesSchemaVersion()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());
        var root = Parse(json);

        root.GetProperty("$schemaVersion").GetString().Should().Be("1.0");
    }

    [Fact]
    public void Serialize_Always_IncludesName()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable("dbo.Bundle"));
        var root = Parse(json);

        root.GetProperty("name").GetString().Should().Be("dbo.Bundle");
    }

    [Fact]
    public void Serialize_Always_IncludesFields()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());
        var root = Parse(json);

        root.GetProperty("fields").GetArrayLength().Should().Be(1);
    }

    // ── SourceFile excluded ───────────────────────────────────────────────────

    [Fact]
    public void Serialize_SourceFile_NotPresentInOutput()
    {
        var table = MinimalTable() with { SourceFile = "tables/dbo.Order.json" };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("sourceFile");
        json.Should().NotContain("SourceFile");
    }

    // ── Empty collections omitted ─────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyForeignKeys_OmittedFromOutput()
    {
        var table = MinimalTable();  // ForeignKeys defaults to []
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("foreignKeys");
    }

    [Fact]
    public void Serialize_EmptyDatabaseTypes_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("databaseTypes");
    }

    [Fact]
    public void Serialize_EmptySets_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("sets");
    }

    [Fact]
    public void Serialize_EmptySections_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("sections");
    }

    [Fact]
    public void Serialize_EmptyPrimaryKey_OmittedFromOutput()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Log",
            Fields = [new FieldDefinition { Name = "Id", Type = "int" }],
        };

        var json = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("primaryKey");
    }

    // ── Empty description omitted ─────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyTableDescription_OmittedFromOutput()
    {
        var table = MinimalTable() with { Description = "" };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("\"description\"");
    }

    [Fact]
    public void Serialize_NonEmptyTableDescription_IncludedInOutput()
    {
        var table = MinimalTable() with { Description = "Core order table" };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().Contain("Core order table");
    }

    [Fact]
    public void Serialize_EmptyShortDescription_OmittedFromOutput()
    {
        var table = MinimalTable() with { ShortDescription = "" };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("\"shortDescription\"");
    }

    [Fact]
    public void Serialize_NonEmptyShortDescription_IncludedInOutput()
    {
        var table = MinimalTable() with { ShortDescription = "Stores active orders" };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().Contain("Stores active orders");
        json.Should().Contain("\"shortDescription\"");
    }

    [Fact]
    public void Serialize_ShortDescriptionAutoGenerated_IncludedWhenTrue()
    {
        var table = MinimalTable() with
        {
            ShortDescription              = "Brief summary",
            ShortDescriptionAutoGenerated = true,
        };
        var json = TableDefinitionSerializer.Serialize(table);

        json.Should().Contain("\"shortDescriptionAutoGenerated\"");
        Parse(json).GetProperty("shortDescriptionAutoGenerated").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_ShortDescriptionAutoGenerated_OmittedWhenNull()
    {
        var table = MinimalTable() with { ShortDescription = "Brief summary", ShortDescriptionAutoGenerated = null };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("\"shortDescriptionAutoGenerated\"");
    }

    // ── False booleans omitted ────────────────────────────────────────────────

    [Fact]
    public void Serialize_IsPrimaryKeyFalse_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Note", Type = "nvarchar(500)", IsPrimaryKey = false }],
        };

        var json  = TableDefinitionSerializer.Serialize(table);
        var field = Parse(json).GetProperty("fields")[0];

        field.TryGetProperty("isPrimaryKey", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_IsPrimaryKeyTrue_PresentInField()
    {
        var table = new TableDefinition
        {
            Name      = "dbo.Order",
            Fields    = [new FieldDefinition { Name = "Id", Type = "int", IsPrimaryKey = true }],
            PrimaryKey = ["Id"],
        };

        var json  = TableDefinitionSerializer.Serialize(table);
        var field = Parse(json).GetProperty("fields")[0];

        field.GetProperty("isPrimaryKey").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_IsMatchColumnFalse_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Id", Type = "int", IsMatchColumn = false }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("isMatchColumn", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_IsMatchColumnTrue_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Code", Type = "varchar(20)", IsMatchColumn = true }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("isMatchColumn").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_CascadeDeleteFalse_OmittedFromFk()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "StatusId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "StatusId", TargetTable = "dbo.Status", TargetField = "Id", CascadeDelete = false }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.TryGetProperty("cascadeDelete", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_SoftFalse_OmittedFromFk()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "StatusId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "StatusId", TargetTable = "dbo.Status", TargetField = "Id" }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.TryGetProperty("soft", out _).Should().BeFalse();
    }

    // ── FK kind serialization ─────────────────────────────────────────────────

    [Fact]
    public void Serialize_PhysicalFk_KindOmittedFromOutput()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "StatusId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "StatusId", TargetTable = "dbo.Status", TargetField = "Id", Kind = ForeignKeyKind.Physical }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.TryGetProperty("kind", out _).Should().BeFalse("Physical is the default and must be omitted to keep files clean");
        fk.TryGetProperty("soft", out _).Should().BeFalse("deprecated 'soft' property must never be written");
    }

    [Fact]
    public void Serialize_LogicalFk_KindWrittenAsLogical()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "CustomerId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "CustomerId", TargetTable = "dbo.Customer", TargetField = "Id", Kind = ForeignKeyKind.Logical }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.GetProperty("kind").GetString().Should().Be("logical");
    }

    [Fact]
    public void Serialize_VirtualFk_KindWrittenAsVirtual()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "RegionId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "RegionId", TargetTable = "dbo.Region", TargetField = "Id", Kind = ForeignKeyKind.Virtual }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.GetProperty("kind").GetString().Should().Be("virtual");
    }

    // ── Table-level labelField serialization ─────────────────────────────────

    [Fact]
    public void Serialize_NullLabelField_LabelFieldOmittedFromOutput()
    {
        var table = MinimalTable();  // LabelField defaults to null

        Parse(TableDefinitionSerializer.Serialize(table)).TryGetProperty("labelField", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_WithLabelField_LabelFieldPresentInOutput()
    {
        var table = MinimalTable() with { LabelField = "szName" };

        Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("labelField").GetString().Should().Be("szName");
    }

    [Fact]
    public void Serialize_FkHasNoLabelField()
    {
        var table = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "CustomerId", Type = "int" }],
            ForeignKeys = [new ForeignKey { SourceField = "CustomerId", TargetTable = "dbo.Customer", TargetField = "Id" }],
        };

        var fk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("foreignKeys")[0];

        fk.TryGetProperty("labelField", out _).Should().BeFalse("labelField is now a table-level property");
    }

    // ── Non-empty collections are present ─────────────────────────────────────

    [Fact]
    public void Serialize_WithSets_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            Sets = [new ColumnSet { Name = "Sync", Columns = ["Id"] }],
        };

        var json = TableDefinitionSerializer.Serialize(table);
        var sets = Parse(json).GetProperty("sets");

        sets.GetArrayLength().Should().Be(1);
        sets[0].GetProperty("name").GetString().Should().Be("Sync");
    }

    [Fact]
    public void Serialize_WithSections_IncludedInOutput()
    {
        var table = MinimalTable() with { Sections = ["orders"] };
        var json  = TableDefinitionSerializer.Serialize(table);

        Parse(json).GetProperty("sections")[0].GetString().Should().Be("orders");
    }

    // ── Default value ─────────────────────────────────────────────────────────

    [Fact]
    public void Serialize_DefaultNull_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Status", Type = "int", Default = null }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("default", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_DefaultSet_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Status", Type = "int", Default = "0" }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("default").GetString().Should().Be("0");
    }

    [Fact]
    public void Serialize_DefaultWithStringLiteral_RoundTripsCorrectly()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Phase", Type = "nvarchar(20)", Default = "'Active'" }],
        };

        var json  = TableDefinitionSerializer.Serialize(table);
        var field = Parse(json).GetProperty("fields")[0];

        field.GetProperty("default").GetString().Should().Be("'Active'");
    }

    // ── Reference table ───────────────────────────────────────────────────────

    [Fact]
    public void Serialize_IsReferenceTableFalse_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("isReferenceTable");
    }

    [Fact]
    public void Serialize_IsReferenceTableTrue_PresentInOutput()
    {
        var table = MinimalTable() with { IsReferenceTable = true };
        var json  = TableDefinitionSerializer.Serialize(table);

        Parse(json).GetProperty("isReferenceTable").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_IsReferenceTableTrue_EmptyData_DataOmittedFromOutput()
    {
        var table = MinimalTable() with { IsReferenceTable = true };
        var json  = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("\"data\"");
    }

    [Fact]
    public void Serialize_IsReferenceTableFalse_DataIgnoredEvenIfPresent()
    {
        // data should never appear when isReferenceTable is false
        var row   = JsonDocument.Parse("{\"Id\":1}").RootElement;
        var table = MinimalTable() with
        {
            IsReferenceTable = false,
            Data = [new Dictionary<string, JsonElement> { ["Id"] = row.GetProperty("Id") }],
        };

        var json = TableDefinitionSerializer.Serialize(table);

        json.Should().NotContain("\"data\"");
        json.Should().NotContain("isReferenceTable");
    }

    [Fact]
    public void Serialize_IsReferenceTableTrue_WithData_DataPresentInOutput()
    {
        var doc   = JsonDocument.Parse("{\"Id\":1,\"State\":\"Active\"}").RootElement;
        var table = new TableDefinition
        {
            Name             = "dbo.Status",
            IsReferenceTable = true,
            Fields           = [new FieldDefinition { Name = "Id", Type = "int" }, new FieldDefinition { Name = "State", Type = "varchar(20)" }],
            PrimaryKey       = ["Id"],
            Data             =
            [
                new Dictionary<string, JsonElement>
                {
                    ["Id"]    = doc.GetProperty("Id"),
                    ["State"] = doc.GetProperty("State"),
                },
            ],
        };

        var root = Parse(TableDefinitionSerializer.Serialize(table));
        var data = root.GetProperty("data");

        data.GetArrayLength().Should().Be(1);
        data[0].GetProperty("Id").GetInt32().Should().Be(1);
        data[0].GetProperty("State").GetString().Should().Be("Active");
    }

    [Fact]
    public async Task Serialize_RoundTrip_ReferenceTableWithData_PreservesAll()
    {
        var doc = JsonDocument.Parse("[{\"Id\":1,\"State\":\"Active\"},{\"Id\":2,\"State\":\"Inactive\"}]").RootElement;
        var original = new TableDefinition
        {
            Name             = "dbo.Status",
            IsReferenceTable = true,
            Fields           =
            [
                new FieldDefinition { Name = "Id",    Type = "int",          Nullable = false },
                new FieldDefinition { Name = "State", Type = "varchar(20)",  Nullable = false },
            ],
            PrimaryKey = ["Id"],
            Data       =
            [
                new Dictionary<string, JsonElement> { ["Id"] = doc[0].GetProperty("Id"), ["State"] = doc[0].GetProperty("State") },
                new Dictionary<string, JsonElement> { ["Id"] = doc[1].GetProperty("Id"), ["State"] = doc[1].GetProperty("State") },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Status.json"), json);

            var loader  = new TableLoader();
            var results = await loader.LoadAsync(tmpDir);
            var loaded  = results.Single();

            loaded.IsReferenceTable.Should().BeTrue();
            loaded.Data.Should().HaveCount(2);
            loaded.Data[0]["Id"].GetInt32().Should().Be(1);
            loaded.Data[0]["State"].GetString().Should().Be("Active");
            loaded.Data[1]["Id"].GetInt32().Should().Be(2);
            loaded.Data[1]["State"].GetString().Should().Be("Inactive");
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // ── Output is indented ────────────────────────────────────────────────────

    [Fact]
    public void Serialize_OutputIsIndented()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        // Indented JSON contains newlines
        json.Should().Contain(Environment.NewLine);
    }

    // ── Round-trip via TableLoader deserialization ─────────────────────────────

    [Fact]
    public async Task Serialize_RoundTrip_DeserializesBackToEquivalentDefinition()
    {
        var original = new TableDefinition
        {
            Name          = "dbo.Bundle",
            Description   = "Product bundle",
            Fields        =
            [
                new FieldDefinition { Name = "Id",          Type = "int",           IsPrimaryKey = true,  Nullable = false },
                new FieldDefinition { Name = "Description", Type = "nvarchar(200)", Nullable = true,  Description = "Bundle description" },
                new FieldDefinition { Name = "StatusId",    Type = "int",           Nullable = false, IsMatchColumn = true, Default = "1" },
            ],
            PrimaryKey    = ["Id"],
            ForeignKeys   =
            [
                new ForeignKey { SourceField = "StatusId", TargetTable = "dbo.BundleStatus", TargetField = "Id", CascadeDelete = true },
            ],
            DatabaseTypes = ["MSSQL"],
            Sections      = ["bundles"],
        };

        // Serialize to JSON, write to an isolated temp directory, load back via TableLoader
        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            var tmpFile = Path.Combine(tmpDir, "dbo.Bundle.json");
            await File.WriteAllTextAsync(tmpFile, json);

            var loader  = new TableLoader();
            var results = await loader.LoadAsync(tmpDir);

            results.Should().HaveCount(1);
            var loaded = results[0];

            loaded!.Name.Should().Be(original.Name);
            loaded.Description.Should().Be(original.Description);
            loaded.PrimaryKey.Should().Equal(original.PrimaryKey);
            loaded.DatabaseTypes.Should().Equal(original.DatabaseTypes);
            loaded.Sections.Should().Equal(original.Sections);

            loaded.Fields.Should().HaveCount(3);
            loaded.Fields[0].Name.Should().Be("Id");
            loaded.Fields[0].IsPrimaryKey.Should().BeTrue();
            loaded.Fields[1].Description.Should().Be("Bundle description");
            loaded.Fields[2].IsMatchColumn.Should().BeTrue();
            loaded.Fields[2].Default.Should().Be("1");

            loaded.ForeignKeys.Should().HaveCount(1);
            loaded.ForeignKeys[0].CascadeDelete.Should().BeTrue();
            loaded.ForeignKeys[0].Kind.Should().Be(ForeignKeyKind.Physical);
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    [Fact]
    public async Task Serialize_RoundTrip_TableWithLabelField_PreservesLabelField()
    {
        var original = new TableDefinition
        {
            Name       = "dbo.Customer",
            Fields     = [new FieldDefinition { Name = "Id", Type = "int", Nullable = false }, new FieldDefinition { Name = "szName", Type = "nvarchar(100)", Nullable = false }],
            LabelField = "szName",
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Customer.json"), json);

            var loader  = new TableLoader();
            var results = await loader.LoadAsync(tmpDir);

            results.Single().LabelField.Should().Be("szName");
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // ── Computed columns ──────────────────────────────────────────────────────

    [Fact]
    public void Serialize_ComputedColumn_IsComputedFalse_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Id", Type = "int", IsComputed = false }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("isComputed", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_ComputedColumn_IsComputedTrue_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "FullName", Type = "nvarchar(101)", IsComputed = true, ComputedExpression = "([First]+' '+[Last])" }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("isComputed").GetBoolean().Should().BeTrue();
        field.GetProperty("computedExpression").GetString().Should().Be("([First]+' '+[Last])");
    }

    [Fact]
    public void Serialize_ComputedColumn_IsPersistedFalse_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "FullName", Type = "nvarchar(101)", IsComputed = true, ComputedExpression = "([First]+' '+[Last])", IsPersisted = false }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("isPersisted", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_ComputedColumn_IsPersistedTrue_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "FullName", Type = "nvarchar(101)", IsComputed = true, ComputedExpression = "([First]+' '+[Last])", IsPersisted = true }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("isPersisted").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public async Task Serialize_RoundTrip_ComputedColumn_PreservesAllComputedProperties()
    {
        var original = new TableDefinition
        {
            Name   = "dbo.Employee",
            Fields =
            [
                new FieldDefinition { Name = "Id",       Type = "int",           Nullable = false },
                new FieldDefinition { Name = "FullName", Type = "nvarchar(201)", Nullable = true,
                                      IsComputed = true, ComputedExpression = "([First]+' '+[Last])", IsPersisted = true },
            ],
            PrimaryKey = ["Id"],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Employee.json"), json);

            var loader  = new TableLoader();
            var results = await loader.LoadAsync(tmpDir);
            var loaded  = results.Single();
            var field   = loaded.Fields.Single(f => f.Name == "FullName");

            field.IsComputed.Should().BeTrue();
            field.ComputedExpression.Should().Be("([First]+' '+[Last])");
            field.IsPersisted.Should().BeTrue();
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    [Fact]
    public async Task Serialize_RoundTrip_VirtualFk_PreservesKind()
    {
        var original = new TableDefinition
        {
            Name        = "dbo.Order",
            Fields      = [new FieldDefinition { Name = "RegionId", Type = "int", Nullable = true }],
            ForeignKeys =
            [
                new ForeignKey
                {
                    SourceField = "RegionId",
                    TargetTable = "dbo.Region",
                    TargetField = "Id",
                    Kind        = ForeignKeyKind.Virtual,
                },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);

            var loader  = new TableLoader();
            var results = await loader.LoadAsync(tmpDir);

            results.Single().ForeignKeys.Single().Kind.Should().Be(ForeignKeyKind.Virtual);
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // ── Inferred foreign keys ─────────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyInferredForeignKeys_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("inferredForeignKeys");
    }

    [Fact]
    public void Serialize_WithInferredForeignKey_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            InferredForeignKeys =
            [
                new InferredRelationship
                {
                    ChildTable   = "dbo.Order",
                    ChildColumn  = "CustomerId",
                    ParentTable  = "dbo.Customer",
                    ParentColumn = "Id",
                    Confidence   = 0.87,
                    Signals      = new SignalScores { Naming = 0.9, Data = 0.85, Query = 0.92, Semantic = 0.75 },
                    Status       = InferredRelationshipStatus.Pending,
                },
            ],
        };

        var root = Parse(TableDefinitionSerializer.Serialize(table));
        var ifk  = root.GetProperty("inferredForeignKeys")[0];

        ifk.GetProperty("childTable").GetString().Should().Be("dbo.Order");
        ifk.GetProperty("childColumn").GetString().Should().Be("CustomerId");
        ifk.GetProperty("parentTable").GetString().Should().Be("dbo.Customer");
        ifk.GetProperty("parentColumn").GetString().Should().Be("Id");
        ifk.GetProperty("confidence").GetDouble().Should().Be(0.87);
        ifk.GetProperty("status").GetString().Should().Be("pending");
    }

    [Fact]
    public void Serialize_InferredForeignKey_StatusValues_SerializedAsLowerCaseStrings()
    {
        static string StatusJson(InferredRelationshipStatus status)
        {
            var table = MinimalTable() with
            {
                InferredForeignKeys =
                [
                    new InferredRelationship
                    {
                        ChildTable = "dbo.A", ChildColumn = "X",
                        ParentTable = "dbo.B", ParentColumn = "Y",
                        Confidence = 0.5, Signals = new SignalScores(),
                        Status = status,
                    },
                ],
            };
            return Parse(TableDefinitionSerializer.Serialize(table))
                .GetProperty("inferredForeignKeys")[0]
                .GetProperty("status").GetString()!;
        }

        StatusJson(InferredRelationshipStatus.Pending).Should().Be("pending");
        StatusJson(InferredRelationshipStatus.Accepted).Should().Be("accepted");
        StatusJson(InferredRelationshipStatus.Rejected).Should().Be("rejected");
    }

    [Fact]
    public void Serialize_InferredForeignKey_EmptyMissingSignals_OmittedFromOutput()
    {
        var table = MinimalTable() with
        {
            InferredForeignKeys =
            [
                new InferredRelationship
                {
                    ChildTable = "dbo.A", ChildColumn = "X",
                    ParentTable = "dbo.B", ParentColumn = "Y",
                    Confidence = 0.5,
                    Signals    = new SignalScores { Naming = 0.5 },
                    MissingSignals = [],
                    Status     = InferredRelationshipStatus.Pending,
                },
            ],
        };

        var ifk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("inferredForeignKeys")[0];

        ifk.TryGetProperty("missingSignals", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_InferredForeignKey_WithMissingSignals_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            InferredForeignKeys =
            [
                new InferredRelationship
                {
                    ChildTable     = "dbo.A", ChildColumn = "X",
                    ParentTable    = "dbo.B", ParentColumn = "Y",
                    Confidence     = 0.5,
                    Signals        = new SignalScores { Naming = 0.5 },
                    MissingSignals = ["query", "data"],
                    Status         = InferredRelationshipStatus.Pending,
                },
            ],
        };

        var ifk = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("inferredForeignKeys")[0];
        var ms  = ifk.GetProperty("missingSignals");

        ms.GetArrayLength().Should().Be(2);
        ms[0].GetString().Should().Be("query");
        ms[1].GetString().Should().Be("data");
    }

    // ── Deprecation — table ───────────────────────────────────────────────────

    [Fact]
    public void Serialize_IsDeprecatedFalse_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("isDeprecated");
    }

    [Fact]
    public void Serialize_IsDeprecatedTrue_PresentInOutput()
    {
        var table = MinimalTable() with { IsDeprecated = true };
        var root  = Parse(TableDefinitionSerializer.Serialize(table));

        root.GetProperty("isDeprecated").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_DeprecationMessageNull_OmittedFromOutput()
    {
        var table = MinimalTable() with { IsDeprecated = true };
        var root  = Parse(TableDefinitionSerializer.Serialize(table));

        root.TryGetProperty("deprecationMessage", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_DeprecationMessageSet_PresentInOutput()
    {
        var table = MinimalTable() with { IsDeprecated = true, DeprecationMessage = "Use dbo.NewOrder instead." };
        var root  = Parse(TableDefinitionSerializer.Serialize(table));

        root.GetProperty("deprecationMessage").GetString().Should().Be("Use dbo.NewOrder instead.");
    }

    [Fact]
    public async Task Serialize_RoundTrip_DeprecatedTable_PreservesAll()
    {
        var original = MinimalTable() with { IsDeprecated = true, DeprecationMessage = "Replaced by v2." };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();

            loaded.IsDeprecated.Should().BeTrue();
            loaded.DeprecationMessage.Should().Be("Replaced by v2.");
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    // ── Deprecation — field ───────────────────────────────────────────────────

    [Fact]
    public void Serialize_FieldIsDeprecatedFalse_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Id", Type = "int", IsDeprecated = false }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("isDeprecated", out _).Should().BeFalse();
    }

    [Fact]
    public void Serialize_FieldIsDeprecatedTrue_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "OldCode", Type = "nvarchar(10)", IsDeprecated = true }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("isDeprecated").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public void Serialize_FieldDeprecationMessageSet_PresentInField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "OldCode", Type = "nvarchar(10)", IsDeprecated = true, DeprecationMessage = "Use NewCode." }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("deprecationMessage").GetString().Should().Be("Use NewCode.");
    }

    [Fact]
    public async Task Serialize_RoundTrip_DeprecatedField_PreservesAll()
    {
        var original = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "OldCode", Type = "nvarchar(10)", IsDeprecated = true, DeprecationMessage = "Use NewCode." }],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();
            var field  = loaded.Fields[0];

            field.IsDeprecated.Should().BeTrue();
            field.DeprecationMessage.Should().Be("Use NewCode.");
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    // ── Sensitivity ───────────────────────────────────────────────────────────

    [Fact]
    public void Serialize_SensitivityNull_OmittedFromField()
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Id", Type = "int" }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.TryGetProperty("sensitivity", out _).Should().BeFalse();
    }

    [Theory]
    [InlineData("pii")]
    [InlineData("confidential")]
    [InlineData("internal")]
    [InlineData("public")]
    public void Serialize_SensitivityValue_RoundTrips(string sensitivityValue)
    {
        var table = new TableDefinition
        {
            Name   = "dbo.Order",
            Fields = [new FieldDefinition { Name = "Email", Type = "nvarchar(255)", Sensitivity = sensitivityValue }],
        };

        var field = Parse(TableDefinitionSerializer.Serialize(table)).GetProperty("fields")[0];

        field.GetProperty("sensitivity").GetString().Should().Be(sensitivityValue);
    }

    [Fact]
    public async Task Serialize_RoundTrip_Sensitivity_PreservesValue()
    {
        var original = new TableDefinition
        {
            Name   = "dbo.Customer",
            Fields = [new FieldDefinition { Name = "Email", Type = "nvarchar(255)", Sensitivity = "pii" }],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Customer.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();

            loaded.Fields[0].Sensitivity.Should().Be("pii");
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    // ── Indexes ───────────────────────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyIndexes_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("indexes");
    }

    [Fact]
    public void Serialize_WithIndex_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            Indexes =
            [
                new IndexDefinition
                {
                    Name       = "IX_Order_Status",
                    Columns    = ["StatusId"],
                    IsUnique   = true,
                    IsClustered = false,
                },
            ],
        };

        var root = Parse(TableDefinitionSerializer.Serialize(table));
        var idx  = root.GetProperty("indexes")[0];

        idx.GetProperty("name").GetString().Should().Be("IX_Order_Status");
        idx.GetProperty("columns")[0].GetString().Should().Be("StatusId");
        idx.GetProperty("isUnique").GetBoolean().Should().BeTrue();
    }

    [Fact]
    public async Task Serialize_RoundTrip_Indexes_PreservesAll()
    {
        var original = MinimalTable() with
        {
            Indexes =
            [
                new IndexDefinition
                {
                    Name             = "IX_Covering",
                    Columns          = ["CustomerId", "StatusId"],
                    IsUnique         = false,
                    IsClustered      = false,
                    IsFiltered       = true,
                    FilterExpression = "[StatusId] = 1",
                    IncludedColumns  = "Description",
                },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();
            var idx    = loaded.Indexes[0];

            idx.Name.Should().Be("IX_Covering");
            idx.Columns.Should().Equal("CustomerId", "StatusId");
            idx.IsFiltered.Should().BeTrue();
            idx.FilterExpression.Should().Be("[StatusId] = 1");
            idx.IncludedColumns.Should().Be("Description");
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    // ── CheckConstraints ──────────────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyCheckConstraints_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("checkConstraints");
    }

    [Fact]
    public void Serialize_WithCheckConstraint_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            CheckConstraints =
            [
                new CheckConstraint { Name = "CK_Order_Amount", Expression = "[Amount] > 0", Column = "Amount" },
            ],
        };

        var root = Parse(TableDefinitionSerializer.Serialize(table));
        var cc   = root.GetProperty("checkConstraints")[0];

        cc.GetProperty("name").GetString().Should().Be("CK_Order_Amount");
        cc.GetProperty("expression").GetString().Should().Be("[Amount] > 0");
        cc.GetProperty("column").GetString().Should().Be("Amount");
    }

    [Fact]
    public async Task Serialize_RoundTrip_CheckConstraints_PreservesAll()
    {
        var original = MinimalTable() with
        {
            CheckConstraints =
            [
                new CheckConstraint { Name = "CK_Status", Expression = "[StatusId] IN (1,2,3)" },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();
            var cc     = loaded.CheckConstraints[0];

            cc.Name.Should().Be("CK_Status");
            cc.Expression.Should().Be("[StatusId] IN (1,2,3)");
            cc.Column.Should().BeNull();
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    // ── UniqueConstraints ─────────────────────────────────────────────────────

    [Fact]
    public void Serialize_EmptyUniqueConstraints_OmittedFromOutput()
    {
        var json = TableDefinitionSerializer.Serialize(MinimalTable());

        json.Should().NotContain("uniqueConstraints");
    }

    [Fact]
    public void Serialize_WithUniqueConstraint_IncludedInOutput()
    {
        var table = MinimalTable() with
        {
            UniqueConstraints =
            [
                new UniqueConstraint { Name = "UQ_Order_Code", Columns = ["Code"] },
            ],
        };

        var root = Parse(TableDefinitionSerializer.Serialize(table));
        var uc   = root.GetProperty("uniqueConstraints")[0];

        uc.GetProperty("name").GetString().Should().Be("UQ_Order_Code");
        uc.GetProperty("columns")[0].GetString().Should().Be("Code");
    }

    [Fact]
    public async Task Serialize_RoundTrip_UniqueConstraints_PreservesAll()
    {
        var original = MinimalTable() with
        {
            UniqueConstraints =
            [
                new UniqueConstraint { Name = "UQ_Order_ExternalRef", Columns = ["ExternalId", "SourceSystem"] },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);
            var loaded = (await new TableLoader().LoadAsync(tmpDir)).Single();
            var uc     = loaded.UniqueConstraints[0];

            uc.Name.Should().Be("UQ_Order_ExternalRef");
            uc.Columns.Should().Equal("ExternalId", "SourceSystem");
        }
        finally { Directory.Delete(tmpDir, recursive: true); }
    }

    [Fact]
    public void Serialize_InferredForeignKey_NullSignalScores_OmittedFromSignals()
    {
        var table = MinimalTable() with
        {
            InferredForeignKeys =
            [
                new InferredRelationship
                {
                    ChildTable  = "dbo.A", ChildColumn = "X",
                    ParentTable = "dbo.B", ParentColumn = "Y",
                    Confidence  = 0.5,
                    Signals     = new SignalScores { Naming = 0.8 },  // only Naming set
                    Status      = InferredRelationshipStatus.Pending,
                },
            ],
        };

        var signals = Parse(TableDefinitionSerializer.Serialize(table))
            .GetProperty("inferredForeignKeys")[0]
            .GetProperty("signals");

        signals.GetProperty("naming").GetDouble().Should().Be(0.8);
        signals.TryGetProperty("data",     out _).Should().BeFalse();
        signals.TryGetProperty("query",    out _).Should().BeFalse();
        signals.TryGetProperty("semantic", out _).Should().BeFalse();
    }

    [Fact]
    public async Task Serialize_RoundTrip_InferredForeignKey_PreservesAll()
    {
        var original = MinimalTable() with
        {
            InferredForeignKeys =
            [
                new InferredRelationship
                {
                    ChildTable     = "dbo.Order",
                    ChildColumn    = "CustomerId",
                    ParentTable    = "dbo.Customer",
                    ParentColumn   = "Id",
                    Confidence     = 0.92,
                    Signals        = new SignalScores { Naming = 1.0, Data = 0.85, Semantic = 0.90 },
                    MissingSignals = ["query"],
                    Status         = InferredRelationshipStatus.Accepted,
                },
            ],
        };

        var json   = TableDefinitionSerializer.Serialize(original);
        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        try
        {
            await File.WriteAllTextAsync(Path.Combine(tmpDir, "dbo.Order.json"), json);

            var loader = new TableLoader();
            var loaded = (await loader.LoadAsync(tmpDir)).Single();

            loaded.InferredForeignKeys.Should().HaveCount(1);
            var ifk = loaded.InferredForeignKeys[0];

            ifk.ChildTable.Should().Be("dbo.Order");
            ifk.ChildColumn.Should().Be("CustomerId");
            ifk.ParentTable.Should().Be("dbo.Customer");
            ifk.ParentColumn.Should().Be("Id");
            ifk.Confidence.Should().Be(0.92);
            ifk.Signals.Naming.Should().Be(1.0);
            ifk.Signals.Data.Should().Be(0.85);
            ifk.Signals.Query.Should().BeNull();
            ifk.Signals.Semantic.Should().Be(0.90);
            ifk.MissingSignals.Should().Equal("query");
            ifk.Status.Should().Be(InferredRelationshipStatus.Accepted);
        }
        finally
        {
            Directory.Delete(tmpDir, recursive: true);
        }
    }
}
