using System.Text.Json;
using System.Text.Json.Serialization;

namespace Manifesta.Core.IR;

// ─── Top-level container ───────────────────────────────────────────────────

/// <summary>
/// The root of the Manifesta internal representation.
/// Constructed once per run after Load + Validate phases.
/// </summary>
public sealed record ManifestRoot
{
    public IReadOnlyList<TableDefinition> Tables { get; init; } = [];
    public IReadOnlyList<ApiDefinition>   Apis   { get; init; } = [];
    public IReadOnlyList<SectionDefinition> Sections { get; init; } = [];
}

// ─── Database / Table IR ──────────────────────────────────────────────────

/// <summary>
/// Fully resolved table definition. Populated by TableLoader, enriched by graph resolution.
/// </summary>
public sealed record TableDefinition
{
    /// <summary>Logical table name, e.g. "dbo.Customer"</summary>
    public required string Name { get; init; }

    public string Description { get; init; } = "";

    /// <summary>
    /// When <c>true</c>, the description was generated by AI and is safe to overwrite.
    /// When <c>false</c> or absent, the description is human-owned and must not be modified automatically.
    /// </summary>
    public bool? DescriptionAutoGenerated { get; init; }

    /// <summary>One-liner shown in the Table of Contents. Kept deliberately short (≤15 words).</summary>
    public string ShortDescription { get; init; } = "";

    /// <summary>
    /// When <c>true</c>, <see cref="ShortDescription"/> was generated by AI and is safe to overwrite.
    /// When <c>false</c> or absent, it is human-owned and must not be modified automatically.
    /// </summary>
    public bool? ShortDescriptionAutoGenerated { get; init; }

    /// <summary>When <c>true</c>, this table is deprecated and should no longer be used.</summary>
    public bool IsDeprecated { get; init; }

    /// <summary>Optional message explaining why the table is deprecated and what to use instead.</summary>
    public string? DeprecationMessage { get; init; }

    public IReadOnlyList<FieldDefinition> Fields { get; init; } = [];

    /// <summary>One or more field names that form the primary key.</summary>
    public IReadOnlyList<string> PrimaryKey { get; init; } = [];

    public IReadOnlyList<ForeignKey> ForeignKeys { get; init; } = [];

    /// <summary>Database-type tags (e.g. ["MSSQL", "Postgres"]).</summary>
    public IReadOnlyList<string> DatabaseTypes { get; init; } = [];

    /// <summary>Named column sets defined on this table.</summary>
    public IReadOnlyList<ColumnSet> Sets { get; init; } = [];

    /// <summary>Section membership (resolved from section definition files).</summary>
    public IReadOnlyList<string> Sections { get; init; } = [];

    /// <summary>Source file path — used for error reporting.</summary>
    public string SourceFile { get; init; } = "";

    /// <summary>Whether this table is a reference/lookup table.</summary>
    public bool IsReferenceTable { get; init; }

    /// <summary>
    /// Field name that holds the human-readable label for this table.
    /// Used by AI description generation and documentation rendering when this table is referenced as a FK target.
    /// Repo-sovereign — never modified by db merge.
    /// </summary>
    public string? LabelField { get; init; }

    /// <summary>
    /// Complete row data for reference tables. Only populated when IsReferenceTable == true.
    /// Repo-curated: never auto-modified by db merge; can be refreshed with --force-capture-reference-data.
    /// JsonElement values ensure correct STJ roundtrip without boxing.
    /// </summary>
    public IReadOnlyList<IReadOnlyDictionary<string, JsonElement>> Data { get; init; } = [];

    /// <summary>
    /// Relationships inferred by <c>manifesta ai infer</c>.
    /// Stored as virtual foreign keys with a confidence score and human-reviewable status.
    /// Repo-sovereign — never modified by db merge.
    /// </summary>
    public IReadOnlyList<InferredRelationship> InferredForeignKeys { get; init; } = [];

    /// <summary>
    /// Non-clustered, unique, and covering indexes on this table.
    /// DB-authoritative — always replaced from live introspection by db merge/export.
    /// </summary>
    public IReadOnlyList<IndexDefinition> Indexes { get; init; } = [];

    /// <summary>
    /// CHECK constraints defined on this table.
    /// DB-authoritative — always replaced from live introspection by db merge/export.
    /// </summary>
    public IReadOnlyList<CheckConstraint> CheckConstraints { get; init; } = [];

    /// <summary>
    /// Table-level UNIQUE constraints (composite or single-column).
    /// DB-authoritative — always replaced from live introspection by db merge/export.
    /// </summary>
    public IReadOnlyList<UniqueConstraint> UniqueConstraints { get; init; } = [];
}

public sealed record FieldDefinition
{
    public required string Name { get; init; }
    public required string Type { get; init; }
    public bool   Nullable    { get; init; }
    public string Description { get; init; } = "";

    /// <summary>
    /// When <c>true</c>, the description was generated by AI and is safe to overwrite.
    /// When <c>false</c> or absent, the description is human-owned and must not be modified automatically.
    /// </summary>
    public bool? DescriptionAutoGenerated { get; init; }

    /// <summary>True if this field is (or is part of) the primary key.</summary>
    public bool IsPrimaryKey { get; init; }

    /// <summary>
    /// Match column hints — field must be non-nullable and unique.
    /// A warning is emitted if the field is nullable.
    /// </summary>
    public bool IsMatchColumn { get; init; }

    /// <summary>
    /// Default value for the column as defined in the database (e.g. "0", "'Active'", "getdate()").
    /// Null when no default is defined.  DB-authoritative — populated by db export/merge.
    /// </summary>
    public string? Default { get; init; }

    /// <summary>
    /// True when this column is a computed column.
    /// DB-authoritative — populated by db export/merge.
    /// </summary>
    public bool IsComputed { get; init; }

    /// <summary>
    /// The SQL expression for computed columns (e.g. "([FirstName]+' '+[LastName])").
    /// Null for non-computed columns. DB-authoritative.
    /// </summary>
    public string? ComputedExpression { get; init; }

    /// <summary>
    /// True when the computed column is persisted (physically stored).
    /// Always false for non-computed columns. DB-authoritative.
    /// </summary>
    public bool IsPersisted { get; init; }

    /// <summary>When <c>true</c>, this field is deprecated and should no longer be used.</summary>
    public bool IsDeprecated { get; init; }

    /// <summary>Optional message explaining why the field is deprecated and what to use instead.</summary>
    public string? DeprecationMessage { get; init; }

    /// <summary>
    /// Data sensitivity classification. Repo-sovereign — never modified by db merge.
    /// Accepted values: <c>"public"</c>, <c>"internal"</c>, <c>"confidential"</c>, <c>"pii"</c>.
    /// <c>null</c> means unclassified.
    /// </summary>
    public string? Sensitivity { get; init; }
}

// ─── Index / Constraint IR ────────────────────────────────────────────────────

/// <summary>
/// A non-clustered, unique, or covering index on a table.
/// DB-authoritative — populated by db export/merge.
/// </summary>
public sealed record IndexDefinition
{
    public required string Name { get; init; }

    /// <summary>Ordered list of key columns included in the index.</summary>
    public IReadOnlyList<string> Columns { get; init; } = [];

    public bool IsUnique    { get; init; }
    public bool IsClustered { get; init; }
    public bool IsFiltered  { get; init; }

    /// <summary>Filter predicate for filtered indexes (e.g. "([IsDeleted]=(0))").</summary>
    public string? FilterExpression { get; init; }

    /// <summary>Comma-joined list of included (non-key) columns.</summary>
    public string? IncludedColumns { get; init; }

    public string? Description { get; init; }
    public bool?   DescriptionAutoGenerated { get; init; }
}

/// <summary>
/// A CHECK constraint on a table.
/// DB-authoritative — populated by db export/merge.
/// </summary>
public sealed record CheckConstraint
{
    public required string Name       { get; init; }
    public required string Expression { get; init; }

    /// <summary>Column name when the constraint applies to a single column; null for table-level constraints.</summary>
    public string? Column { get; init; }
}

/// <summary>
/// A UNIQUE constraint on a table (may span multiple columns).
/// DB-authoritative — populated by db export/merge.
/// </summary>
public sealed record UniqueConstraint
{
    public required string Name { get; init; }
    public IReadOnlyList<string> Columns { get; init; } = [];
}

/// <summary>
/// Classifies the nature of a foreign key relationship.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<ForeignKeyKind>))]
public enum ForeignKeyKind
{
    /// <summary>Database-enforced foreign key constraint. DB-authoritative.</summary>
    [JsonStringEnumMemberName("physical")]
    Physical,

    /// <summary>Business-logic relationship expected to exist in data but not DB-enforced. Repo-sovereign.</summary>
    [JsonStringEnumMemberName("logical")]
    Logical,

    /// <summary>Documentation-only conceptual link. Repo-sovereign.</summary>
    [JsonStringEnumMemberName("virtual")]
    Virtual,
}

[JsonConverter(typeof(ForeignKeyJsonConverter))]
public sealed record ForeignKey
{
    public required string SourceField  { get; init; }
    public required string TargetTable  { get; init; }
    public required string TargetField  { get; init; }

    /// <summary>Whether cascade delete is expected. Applies to Physical relationships only.</summary>
    public bool CascadeDelete { get; init; }

    /// <summary>
    /// Relationship kind. Default is <see cref="ForeignKeyKind.Physical"/>.
    /// Logical and Virtual relationships are repo-sovereign and never modified by db merge.
    /// </summary>
    public ForeignKeyKind Kind { get; init; }

}

/// <summary>
/// A named subset of columns (used for sync set expansion).
/// </summary>
public sealed record ColumnSet
{
    public required string Name    { get; init; }
    public IReadOnlyList<string> Columns { get; init; } = [];
}

// ─── Section IR ───────────────────────────────────────────────────────────

/// <summary>
/// Defines a single auto-generated Mermaid ERD embedded in a section.
/// </summary>
public sealed record ErdDefinition
{
    /// <summary>Optional heading rendered above the diagram.</summary>
    public string? Title { get; init; }

    /// <summary>
    /// Subset of section tables to include. Empty = all section tables.
    /// Every name must also appear in the owning section's <c>tables</c> array.
    /// </summary>
    public IReadOnlyList<string> Tables { get; init; } = [];

    /// <summary>
    /// Whether to include Logical FKs in the diagram.
    /// <c>null</c> means default behaviour: include (equivalent to <c>true</c>).
    /// Set to <c>false</c> via <c>--no-logical</c> to exclude them.
    /// </summary>
    public bool? IncludeLogical { get; init; }

    /// <summary>Whether to include Virtual FKs as dashed lines. Default false.</summary>
    public bool IncludeVirtual { get; init; }

    /// <summary>
    /// Which fields to show inside each entity box.
    /// Accepted values: <c>"none"</c>, <c>"pk-and-fk"</c>, <c>"all"</c>.
    /// Default: <c>"pk-and-fk"</c>.
    /// </summary>
    public string Fields { get; init; } = ErdFields.PkAndFk;
}

/// <summary>
/// Well-known values for <see cref="ErdDefinition.Fields"/>.
/// </summary>
public static class ErdFields
{
    public const string None    = "none";
    public const string PkAndFk = "pk-and-fk";
    public const string All     = "all";
}

/// <summary>
/// A logical grouping of tables for documentation purposes.
/// </summary>
public sealed record SectionDefinition
{
    /// <summary>
    /// Stable kebab-case identifier used for <c>sectionOrder</c> matching in
    /// <c>manifesta.config.json</c>. Never displayed to end users.
    /// </summary>
    public required string Name        { get; init; }

    /// <summary>
    /// Human-readable heading used in the TOC and section headings.
    /// Falls back to <see cref="Name"/> when not set, so existing section
    /// files that don't include a <c>title</c> field continue to work unchanged.
    /// </summary>
    public string? Title               { get; init; }

    /// <summary>Returns <see cref="Title"/> if set, otherwise <see cref="Name"/>.</summary>
    public string DisplayTitle         => Title ?? Name;

    public string Description          { get; init; } = "";
    public IReadOnlyList<string> Tables { get; init; } = [];

    /// <summary>Auto-generated Mermaid ERD diagrams for this section.</summary>
    public IReadOnlyList<ErdDefinition> Erds { get; init; } = [];

    public string SourceFile           { get; init; } = "";
}

// ─── API IR ───────────────────────────────────────────────────────────────

/// <summary>
/// A single API (Swagger/OpenAPI document).
/// </summary>
public sealed record ApiDefinition
{
    public required string Name        { get; init; }
    public required string Title       { get; init; }
    public required string Version     { get; init; }
    public string Description          { get; init; } = "";
    public IReadOnlyList<EndpointDefinition> Endpoints { get; init; } = [];
    public IReadOnlyList<string> DatabaseTypes          { get; init; } = [];
    public string SourceFile                            { get; init; } = "";
}

public sealed record EndpointDefinition
{
    public required string Path        { get; init; }
    public required string Method      { get; init; }  // GET, POST, …
    public string          Summary     { get; init; } = "";
    public IReadOnlyList<string> Tags  { get; init; } = [];

    // Custom extensions
    public string?              DbTable     { get; init; }  // x-db-table
    public string?              DbOperation { get; init; }  // x-db-operation
    public IReadOnlyList<string> DatabaseTypes { get; init; } = [];  // x-databaseTypes
}

// ─── AI Infer IR ─────────────────────────────────────────────────────────

/// <summary>
/// Per-signal scores from the <c>ai infer</c> scoring pipeline.
/// Null means the signal was not computed for this pair.
/// </summary>
public sealed record SignalScores
{
    public double? Naming   { get; init; }
    public double? Data     { get; init; }
    public double? Query    { get; init; }
    public double? Semantic { get; init; }
}

/// <summary>
/// Status of an inferred relationship — tracks whether a human has reviewed it.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<InferredRelationshipStatus>))]
public enum InferredRelationshipStatus
{
    [JsonStringEnumMemberName("pending")]
    Pending,

    [JsonStringEnumMemberName("accepted")]
    Accepted,

    [JsonStringEnumMemberName("rejected")]
    Rejected,
}

/// <summary>
/// A relationship inferred by <c>manifesta ai infer</c> using multi-signal analysis.
/// Stored as a virtual foreign key in the table definition file with a confidence score
/// and a human-reviewable status.
/// </summary>
public sealed record InferredRelationship
{
    public required string ChildTable   { get; init; }
    public required string ChildColumn  { get; init; }
    public required string ParentTable  { get; init; }
    public required string ParentColumn { get; init; }

    /// <summary>Composite confidence score in the range 0.0 – 1.0.</summary>
    public required double Confidence { get; init; }

    public required SignalScores Signals { get; init; }

    /// <summary>Signal names that could not be computed for this pair (e.g. "query").</summary>
    public IReadOnlyList<string> MissingSignals { get; init; } = [];

    public required InferredRelationshipStatus Status { get; init; }
}

// ─── Schema Graph IR ──────────────────────────────────────────────────────

/// <summary>
/// The FK dependency graph. Constructed by SchemaGraphBuilder (M1).
/// </summary>
public sealed record SchemaGraph
{
    public IReadOnlyList<TableDefinition> Nodes { get; init; } = [];

    /// <summary>Directed edges: (source table name) → (target table name)</summary>
    public IReadOnlyList<GraphEdge> Edges { get; init; } = [];
}

public sealed record GraphEdge
{
    public required string SourceTable { get; init; }
    public required string TargetTable { get; init; }
    public required string SourceField { get; init; }
    public required string TargetField { get; init; }
}
