using System.Text.Json;
using System.Text.Json.Serialization;
using Manifesta.Core.IR;

namespace Manifesta.Core;

public static class TableDefinitionSerializer
{
    private static readonly JsonSerializerOptions _options = new()
    {
        WriteIndented        = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static string Serialize(TableDefinition table)
    {
        var dto = new TableDefinitionDto
        {
            SchemaVersion              = "1.0",
            Name                       = table.Name,
            Description                = string.IsNullOrEmpty(table.Description) ? null : table.Description,
            DescriptionAutoGenerated   = table.DescriptionAutoGenerated,
            ShortDescription           = string.IsNullOrEmpty(table.ShortDescription) ? null : table.ShortDescription,
            ShortDescriptionAutoGenerated = table.ShortDescriptionAutoGenerated,
            IsDeprecated               = table.IsDeprecated ? true : null,
            DeprecationMessage         = table.IsDeprecated ? table.DeprecationMessage : null,
            IsReferenceTable           = table.IsReferenceTable ? true : null,
            LabelField    = table.LabelField,
            Fields        = table.Fields.Select(FieldDto.From).ToList(),
            PrimaryKey    = table.PrimaryKey.Count > 0 ? table.PrimaryKey.ToList() : null,
            ForeignKeys   = table.ForeignKeys.Count > 0
                                ? table.ForeignKeys.Select(ForeignKeyDto.From).ToList()
                                : null,
            DatabaseTypes = table.DatabaseTypes.Count > 0 ? table.DatabaseTypes.ToList() : null,
            Sets          = table.Sets.Count > 0 ? table.Sets.Select(ColumnSetDto.From).ToList() : null,
            Sections      = table.Sections.Count > 0 ? table.Sections.ToList() : null,
            Data          = table.IsReferenceTable && table.Data.Count > 0
                                ? table.Data.Select(r => new Dictionary<string, JsonElement>(r)).ToList()
                                : null,
            InferredForeignKeys = table.InferredForeignKeys.Count > 0
                                ? table.InferredForeignKeys.Select(InferredRelationshipDto.From).ToList()
                                : null,
            Indexes = table.Indexes.Count > 0
                                ? table.Indexes.Select(IndexDefinitionDto.From).ToList()
                                : null,
            CheckConstraints = table.CheckConstraints.Count > 0
                                ? table.CheckConstraints.Select(CheckConstraintDto.From).ToList()
                                : null,
            UniqueConstraints = table.UniqueConstraints.Count > 0
                                ? table.UniqueConstraints.Select(UniqueConstraintDto.From).ToList()
                                : null,
        };

        return JsonSerializer.Serialize(dto, _options);
    }

    // ── DTOs ──────────────────────────────────────────────────────────────────

    private sealed class TableDefinitionDto
    {
        [JsonPropertyName("$schemaVersion")]
        public string? SchemaVersion { get; init; }

        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("description")]
        public string? Description { get; init; }

        [JsonPropertyName("descriptionAutoGenerated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? DescriptionAutoGenerated { get; init; }

        [JsonPropertyName("shortDescription")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ShortDescription { get; init; }

        [JsonPropertyName("shortDescriptionAutoGenerated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? ShortDescriptionAutoGenerated { get; init; }

        [JsonPropertyName("isDeprecated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? IsDeprecated { get; init; }

        [JsonPropertyName("deprecationMessage")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? DeprecationMessage { get; init; }

        [JsonPropertyName("isReferenceTable")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? IsReferenceTable { get; init; }

        [JsonPropertyName("labelField")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? LabelField { get; init; }

        [JsonPropertyName("fields")]
        public required List<FieldDto> Fields { get; init; }

        [JsonPropertyName("primaryKey")]
        public List<string>? PrimaryKey { get; init; }

        [JsonPropertyName("foreignKeys")]
        public List<ForeignKeyDto>? ForeignKeys { get; init; }

        [JsonPropertyName("databaseTypes")]
        public List<string>? DatabaseTypes { get; init; }

        [JsonPropertyName("sets")]
        public List<ColumnSetDto>? Sets { get; init; }

        [JsonPropertyName("sections")]
        public List<string>? Sections { get; init; }

        [JsonPropertyName("data")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<Dictionary<string, JsonElement>>? Data { get; init; }

        [JsonPropertyName("inferredForeignKeys")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<InferredRelationshipDto>? InferredForeignKeys { get; init; }

        [JsonPropertyName("indexes")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<IndexDefinitionDto>? Indexes { get; init; }

        [JsonPropertyName("checkConstraints")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<CheckConstraintDto>? CheckConstraints { get; init; }

        [JsonPropertyName("uniqueConstraints")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<UniqueConstraintDto>? UniqueConstraints { get; init; }
    }

    private sealed class FieldDto
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("type")]
        public required string Type { get; init; }

        [JsonPropertyName("nullable")]
        public bool Nullable { get; init; }

        [JsonPropertyName("description")]
        public string? Description { get; init; }

        [JsonPropertyName("descriptionAutoGenerated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? DescriptionAutoGenerated { get; init; }

        [JsonPropertyName("isPrimaryKey")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsPrimaryKey { get; init; }

        [JsonPropertyName("isMatchColumn")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsMatchColumn { get; init; }

        [JsonPropertyName("default")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Default { get; init; }

        [JsonPropertyName("isComputed")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsComputed { get; init; }

        [JsonPropertyName("computedExpression")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ComputedExpression { get; init; }

        [JsonPropertyName("isPersisted")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsPersisted { get; init; }

        [JsonPropertyName("isDeprecated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsDeprecated { get; init; }

        [JsonPropertyName("deprecationMessage")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? DeprecationMessage { get; init; }

        [JsonPropertyName("sensitivity")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Sensitivity { get; init; }

        public static FieldDto From(FieldDefinition f) => new()
        {
            Name                     = f.Name,
            Type                     = f.Type,
            Nullable                 = f.Nullable,
            Description              = string.IsNullOrEmpty(f.Description) ? null : f.Description,
            DescriptionAutoGenerated = f.DescriptionAutoGenerated,
            IsPrimaryKey             = f.IsPrimaryKey,
            IsMatchColumn            = f.IsMatchColumn,
            Default                  = f.Default,
            IsComputed               = f.IsComputed,
            ComputedExpression       = f.ComputedExpression,
            IsPersisted              = f.IsPersisted,
            IsDeprecated             = f.IsDeprecated,
            DeprecationMessage       = f.IsDeprecated ? f.DeprecationMessage : null,
            Sensitivity              = f.Sensitivity,
        };
    }

    private sealed class ForeignKeyDto
    {
        [JsonPropertyName("sourceField")]
        public required string SourceField { get; init; }

        [JsonPropertyName("targetTable")]
        public required string TargetTable { get; init; }

        [JsonPropertyName("targetField")]
        public required string TargetField { get; init; }

        [JsonPropertyName("cascadeDelete")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool CascadeDelete { get; init; }

        [JsonPropertyName("kind")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Kind { get; init; }

        public static ForeignKeyDto From(ForeignKey fk) => new()
        {
            SourceField   = fk.SourceField,
            TargetTable   = fk.TargetTable,
            TargetField   = fk.TargetField,
            CascadeDelete = fk.CascadeDelete,
            Kind          = fk.Kind == ForeignKeyKind.Physical ? null : fk.Kind.ToString().ToLowerInvariant(),
        };
    }

    private sealed class ColumnSetDto
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("columns")]
        public required List<string> Columns { get; init; }

        public static ColumnSetDto From(ColumnSet cs) => new()
        {
            Name    = cs.Name,
            Columns = cs.Columns.ToList(),
        };
    }

    private sealed class InferredRelationshipDto
    {
        [JsonPropertyName("childTable")]
        public required string ChildTable { get; init; }

        [JsonPropertyName("childColumn")]
        public required string ChildColumn { get; init; }

        [JsonPropertyName("parentTable")]
        public required string ParentTable { get; init; }

        [JsonPropertyName("parentColumn")]
        public required string ParentColumn { get; init; }

        [JsonPropertyName("confidence")]
        public required double Confidence { get; init; }

        [JsonPropertyName("signals")]
        public required SignalScoresDto Signals { get; init; }

        [JsonPropertyName("missingSignals")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<string>? MissingSignals { get; init; }

        [JsonPropertyName("status")]
        public required string Status { get; init; }

        public static InferredRelationshipDto From(InferredRelationship r) => new()
        {
            ChildTable     = r.ChildTable,
            ChildColumn    = r.ChildColumn,
            ParentTable    = r.ParentTable,
            ParentColumn   = r.ParentColumn,
            Confidence     = r.Confidence,
            Signals        = SignalScoresDto.From(r.Signals),
            MissingSignals = r.MissingSignals.Count > 0 ? r.MissingSignals.ToList() : null,
            Status         = r.Status.ToString().ToLowerInvariant(),
        };
    }

    private sealed class SignalScoresDto
    {
        [JsonPropertyName("naming")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public double? Naming { get; init; }

        [JsonPropertyName("data")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public double? Data { get; init; }

        [JsonPropertyName("query")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public double? Query { get; init; }

        [JsonPropertyName("semantic")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public double? Semantic { get; init; }

        public static SignalScoresDto From(SignalScores s) => new()
        {
            Naming   = s.Naming,
            Data     = s.Data,
            Query    = s.Query,
            Semantic = s.Semantic,
        };
    }

    private sealed class IndexDefinitionDto
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("columns")]
        public required List<string> Columns { get; init; }

        [JsonPropertyName("isUnique")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsUnique { get; init; }

        [JsonPropertyName("isClustered")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsClustered { get; init; }

        [JsonPropertyName("isFiltered")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool IsFiltered { get; init; }

        [JsonPropertyName("filterExpression")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? FilterExpression { get; init; }

        [JsonPropertyName("includedColumns")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? IncludedColumns { get; init; }

        [JsonPropertyName("description")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Description { get; init; }

        [JsonPropertyName("descriptionAutoGenerated")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? DescriptionAutoGenerated { get; init; }

        public static IndexDefinitionDto From(IndexDefinition idx) => new()
        {
            Name                     = idx.Name,
            Columns                  = idx.Columns.ToList(),
            IsUnique                 = idx.IsUnique,
            IsClustered              = idx.IsClustered,
            IsFiltered               = idx.IsFiltered,
            FilterExpression         = idx.FilterExpression,
            IncludedColumns          = idx.IncludedColumns,
            Description              = string.IsNullOrEmpty(idx.Description) ? null : idx.Description,
            DescriptionAutoGenerated = idx.DescriptionAutoGenerated,
        };
    }

    private sealed class CheckConstraintDto
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("expression")]
        public required string Expression { get; init; }

        [JsonPropertyName("column")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Column { get; init; }

        public static CheckConstraintDto From(CheckConstraint cc) => new()
        {
            Name       = cc.Name,
            Expression = cc.Expression,
            Column     = cc.Column,
        };
    }

    private sealed class UniqueConstraintDto
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        [JsonPropertyName("columns")]
        public required List<string> Columns { get; init; }

        public static UniqueConstraintDto From(UniqueConstraint uc) => new()
        {
            Name    = uc.Name,
            Columns = uc.Columns.ToList(),
        };
    }
}
